[package]
name = "rust-sign"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "2.5.0", features = ["json"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = { version = "1.0.87" }
base64 = { version = "0.13.1" }
srp = { version = "0.6.0", path = "./rustcrypto/srp" }
pbkdf2 = { version = "0.11.0" }
sha2 = { version = "0.10.6" }
rand = { version = "0.8.5" }
rustls = { version = "0.20.7" }
rustls-pemfile = { version = "1.0.1" }
plist = { version = "1.3.1" }
hmac = { version = "0.12.1" }
